routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\DashboardController@index')->name('home');
Route::get('/home', 'Admin\DashboardController@index')->name('home');

Auth::routes();

$settings = array(
  'prefix'    => 'admin',
  'before'    => 'auth|admin',
  'namespace' => 'Admin',
);

Route::group($settings, function($route) 
{
  # User Route
  Route::resource('dashboard', 'DashboardController');
  Route::resource('user', 'UserController');
  Route::any('user/block/{id}/{status}', 'UserController@block');

  Route::resource('sendnotification','SendNotificationController');
  Route::get('admin/sendnotification/show', [

    'uses' => 'SendNotificationController@show',
    'as' => 'admin.sendnotification.show'
]);
  Route::resource('products','ProductController');

  Route::resource('composemail','ComposemailController');
  Route::resource('mailbox','MailboxController');
  Route::resource('readmail','ReadMailController');
  
  Route::resource('button','ButtonsController');
  Route::resource('general','GeneralController');
  Route::resource('icon', 'IconsController');
  Route::resource('modal', 'ModalsController');

  Route::get('change-password','AdminController@showChangePasswordForm');
  Route::post('changePassword','AdminController@changePassword')->name('changePassword');
});

app/Http/Controllers/Admin/SendNotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use Mail;
use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SendNotificationController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        $this->middleware('auth');
        $this->user = $user;
    }


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.sendnotification.index');
    }

    public function show()
    {
        return view('admin.sendnotification.show');
    }
    
    public function store(Request $request)
    {
        $emails = $this->user->pluck('email')->toArray();
        Mail::send('emails.notification', [], function($message) use ($emails)
        {    
            $message->to($emails)->subject('Notification');    
        });
        return redirect()->back()->with("success","Notification sent successfully !");
    }

}

resources/views/admin/sendnotification/index.blade.php
@extends('layouts.app')
@section('content')

<section class="content-header">
<div class="bg-img" style="background-image: url('{{ asset('img/d.png')}}');">
  <form action="{{ route('sendnotification.store') }}" class="container" method="post">
    {{ csrf_field() }}
   <center> <img src="{{ asset('img/e.png')}}" class="brand_logo_container" alt="center" />
    <h1>Sent Notification</h1>
    <p>All registered user will get the same notification that you submit here.</p>

    <label for="tnc"></label>
    <input type="text" placeholder="Type Notification Caption" name="Notification Caption" required>

    <label for="tnd"></label>
    <input type="text" placeholder="Type Notification Description" name=" Notification Description" required>

    <button type="submit" class="btn">Send</button>
  </center>
</form>
</div>
</section>

@endsection

resources/views/admin/sendnotification/show.blade.php
@extends('layouts.app')
@section('content')
<section class="content-header">
     <div class="row">
      
        </div>
    </section>
    <section class="content">
        <div class="container bg-w" style="padding:0px">
              <div class="row">
                  <div class="col-sm-12">
          <h5>Notifications: 15 (Unread)</h5></div></div>
      <div class="row">
        <div class="col-sm-4">
            <img style="    width: 100%;
    display: block; margin: auto;" src="{{ asset('img/Screenshot.png')}}">
        </div>
        <div class="col-sm-8">
              <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
                 <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
                <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
                 <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>  <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
                 <a href="" class="row notification"><div class="col-sm-1"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-11">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row --></div>
    </section>
    @endsection