routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\DashboardController@index')->name('home');
Route::get('/home', 'Admin\DashboardController@index')->name('home');

Auth::routes();

$settings = array(
  'prefix'    => 'admin',
  'before'    => 'auth|admin',
  'namespace' => 'Admin',
);

Route::group($settings, function($route) 
{
  # User Route
  Route::resource('dashboard', 'DashboardController');
  Route::resource('user', 'UserController');
  Route::any('user/block/{id}/{status}', 'UserController@block');

  Route::resource('sendnotification','SendNotificationController');
  Route::get('admin/sendnotification/show', [

    'uses' => 'SendNotificationController@show',
    'as' => 'admin.sendnotification.show'
]);
  Route::resource('products','ProductController');

  Route::resource('composemail','ComposemailController');
  Route::resource('mailbox','MailboxController');
  Route::resource('readmail','ReadMailController');
  
  Route::resource('button','ButtonsController');
  Route::resource('general','GeneralController');
  Route::resource('icon', 'IconsController');
  Route::resource('modal', 'ModalsController');

  Route::get('change-password','AdminController@showChangePasswordForm');
  Route::post('changePassword','AdminController@changePassword')->name('changePassword');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ config('app.name', 'Browsr-Admin') }}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="shortcut icon" href="{{ asset('img/c.png')}}">
  <link rel="stylesheet" href="{{ asset('css/jquery-ui.css')}}">
  <link rel="stylesheet" href="{{ asset('css/userview.css')}}">
  <link rel="stylesheet" href="{{ asset('css/notification.css')}}">
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ asset('css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('css/skins/_all-skins.min.css')}}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{{ asset('css/morris.css')}}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ asset('css/jquery-jvectormap.css')}}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('css/daterangepicker.css')}}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('css/bootstrap3-wysihtml5.min.css')}}">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

 
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
 
 <header class="main-header">
    <!-- Logo -->
    <a href="index.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><img style="width: 100%;
    height: 60px;" src="{{ asset('img/qwe.png')}}" class="img-fluid"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img style="width: 100%;
    height: 68px" src="{{ asset('img/admin.png')}}" class="img-fluid"></span>
    </a>
   
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
             <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="    height: 52px;">
              <i class="fa fa-bell"></i>
              <span class="hidden-xs"></span>
            </a>
            <div class="dropdown-menu" style="min-width: 330px; box-shadow: 0 3px 5px 0 rgba(149, 166, 181, 0.5);">
              <a href="" class="notification"><div class="col-sm-2"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-10">
                     <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
                <a href="" class="notification"><div class="col-sm-2"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-10">
                      <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
              <a href="" class="notification"><div class="col-sm-2"><i class="fa fa-exclamation-circle" aria-hidden="true"></i></div>
                  <div class="col-sm-10">
                      <p> <b>John doe </b>find somethin wrong in <b>Kristen Stewart</b> profile, 
kindly check and take suitable action.</p>
<span>02/13/2020 at 10:00 pm</span>
              </div></a>
              <div class="col-sm-12"><a href="{{ route('admin.sendnotification.show')}}" class="text-center" style="display:block;padding:8px;">See All</a></div>
                </div>
              </li>
          </li>
          <li class="user-menu">
              <p><img src="{{ asset('img/qwerfg.png')}}">Admin</p>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="height:52px;">
              <i class="fa fa-cog"></i>
              <span class="hidden-xs"></span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-footer">
                
                <div>
                  <a href="" data-toggle="modal" data-target="#myModal">Change Password</a>
                </div>
              </li>
              <li class="user-footer">
                
                <div>
                  <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                   document.getElementById('logout-form').submit();">Logout</a>
                                                   <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                    </form>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        
        </ul>
      </div>
    </nav>
  </header>

<!-- Modal -->  
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title text-center">Change Password</h4>
      </div>
      <div class="modal-body ">
        <div class="card">
            <form class="form-horizontal" method="POST" action="{{ route('changePassword') }}">
            {{ csrf_field() }}
                <div>
                <label>Type Your Current Password</label>
                    <div class="input-group" id="show_hide_password">
                  <input class="form-control" type="password" name="current_password" required>
                  <div class="input-group-addon">
                    <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
                </div>
                <div>
                <label>Type Your New Password</label>
                    <div class="input-group" id="show_hide_password">
                  <input class="form-control" type="password" name="new_password" required>
                  <div class="input-group-addon">
                    <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
                </div>
                <div>
                <label>Type Your Confirm New Password</label>
                 <div class="input-group" id="show_hide_password">
                  <input class="form-control" type="password" name="confirm_password" required>
                  <div class="input-group-addon">
                    <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
                 <button type="submit" class="btn btn-change">CHANGE</button>
                </div>
            </form>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

    @guest

    @else
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <br>
      <br>
      <br>
      
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
       <li><a href="{{ route('dashboard.index')}}"><i class="glyphicon glyphicon-dashboard"></i> <span>Dashboard</span></a></li>
        <li class="treeview">
          <li><a href="{{ route('user.index')}}"><i class="glyphicon glyphicon-user"></i> <span>Users</span></a></li>
        </li>
        <li><a href="{{ route('sendnotification.index')}}"><i class="glyphicon glyphicon-send"></i> <span>Sent Notification</span></a></li>
       
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
    @endif
  <!-- Left side column. contains the logo and sidebar -->
 

  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
   @yield('content')
  </div>
 <!-- /.content-wrapper -->
  <!-- jQuery 3 -->
<script src="{{ asset('js/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('js/dist/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('js/dist/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="{{ asset('js/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('js/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('js/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('js/plugins/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('js/plugins/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('js/dist/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('js/moment.min.js') }}"></script>
<script src="{{ asset('js/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('js/dist/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('js/plugins/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('js/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('js/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('js/dist/adminlte.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('js/dist/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('js/dist/demo.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( "#slider-range" ).slider({
      range: true,
      min: 0,
      max: 500,
      values: [ 75, 300 ],
      slide: function( event, ui ) {
        $( "#amount" ).val( "" + ui.values[ 0 ] + " - " + ui.values[ 1 ] );
      }
    });
    $( "#amount" ).val( "" + $( "#slider-range" ).slider( "values", 0 ) +
      " - " + $( "#slider-range" ).slider( "values", 1 ) );
  } );
  </script>
<script>
$(document).ready(function(){
  $('.drag input').change(function () {
    $('.drag p').text(this.files.length + " file(s) selected");
  });
});
</script>
<script>

  $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();

      });

  $(function () {
    var elem = `<div class="popover" role="tooltip"><div class="arrow"></div>
    <h3 class="popover-header"></h3>
    <div class="popover-body"></div>
    </div>`;
    $('[data-toggle="popover"]').popover({
      animation:true, template:elem, html:true
    });
  })
    </script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/1.0.0/dist/progressbar.js"></script>
<script>
    // progressbar.js@1.0.0 version is used
// Docs: http://progressbarjs.readthedocs.org/en/1.0.0/

var bar = new ProgressBar.Circle(maleprogress, {
  color: '#FFEA82',
  trailColor: '#eee',
  trailWidth: 20,
  duration: 1400,
  easing: 'bounce',
  strokeWidth: 6,
  from: {color: '#01f403', a:0},
  to: {color: '#01f403', a:1},
  // Set default step function for all animate calls
  step: function(state, circle) {
    circle.path.setAttribute('stroke', state.color);
  }
});

bar.animate(0.5);  // Number from 0.0 to 1.0



var bar1 = new ProgressBar.Circle(femaleprogress, {
  color: '#FFEA82',
  trailColor: '#eee',
  trailWidth: 20,
  duration: 1400,
  easing: 'bounce',
  strokeWidth: 6,
  from: {color: '#01f403', a:0},
  to: {color: '#01f403', a:1},
  // Set default step function for all animate calls
  step: function(state, circle) {
    circle.path.setAttribute('stroke', state.color);
  }
});

bar1.animate(0.7);  // Number from 0.0 to 1.0
</script>
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{{ asset('img/c.png')}}" type="image/gif" sizes="16x16">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<!------ Include the above in your HEAD tag ---------->
<style type="text/css">
body{
        padding: 89px 0;
}
font{
        font-size: 17px;
    margin-top: 10px;
}
.links a{
        color: #01f403;
    font-weight: 600;
    font-size: 18px;
}
  body,
		html {
			margin: 0;
			height: 100%;
			 background-image: url("{{ asset('img/a.png')}}");  !important;
			 background-size:cover;
		}
		.user_card {
			height: 450px;
    max-width: 406px;width: 100%;
    margin-top: auto;
    margin-bottom: auto;
    background: #FFFFFF;
    position: relative;
    display: flex;
    justify-content: center;
    flex-direction: column;
    padding: 28px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 21px;

		}
		.brand_logo_container {
			position: absolute;
			height: 170px;
			width: 170px;
			top: -75px;
			border-radius: 50%;
			background:#01f403;
			padding: 10px;
			text-align: center;
		}
		.brand_logo {
			height: 150px;
			width: 150px;
			border-radius: 50%;
			border: 2px solid white;
		}
		.form_container {
			margin-top: 100px;
		}
		.login_btn {
		    width: 100%;
    background: #01f403 !important;
    color: white !important;
    border-radius: 18px;
    padding: 8px;
    font-size: 20px;
    font-weight: 600;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #01f403 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.custom-checkbox .custom-control-input:checked~.custom-control-label::before {
			background-color: #c0392b !important;
		}
		.form-control {
    display: block;
    width: 100%;
    height: calc(2.25rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: unset;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    border-bottom: 2px solid #eee;
}
</style>
</head>
<body>
@yield('content')
</body>
</html>